import{a as b,S as L,i as l}from"./assets/vendor-C4-ZuMk8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const w="46892865-5ed871dda5110795735586270",q="https://pixabay.com/api/",S=async(t,s=1,a=15)=>{try{return(await b.get(q,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:a,page:s}})).data}catch(o){throw console.log("Error fetching images:",o),o}};let d;function E(t){const s=document.querySelector(".gallery"),a=t.map(({webformatURL:o,largeImageURL:e,tags:r,likes:i,views:m,comments:f,downloads:h})=>`<li>
          <a href="${e}">
            <div class="image-info">
              <img src="${o}" alt="${r}" width="300" height="200">
              <p><strong>Likes:</strong> ${i}</p>
              <p><strong>Views:</strong> ${m}</p>
              <p><strong>Comments:</strong> ${f}</p>
              <p><strong>Downloads:</strong> ${h}</p>
            </div>
          </a>
        </li>`).join("");s.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new L(".gallery a")}const v=document.querySelector(".search-form"),g=document.querySelector(".loader"),$=document.querySelector(".gallery"),n=document.querySelector(".btn-load");let y="",c=1,u=15;v.addEventListener("submit",async t=>{if(t.preventDefault(),y=t.currentTarget.elements.searchQuery.value.trim(),!y){l.error({title:"Error",message:"Please enter a search query"});return}c=1,$.innerHTML="",n.style.display="none",p()});const p=async()=>{try{g.style.display="block";const t=await S(y,c,u);if(g.style.display="none",t.hits.length===0){l.info({message:"На жаль, немає зображень, які відповідають вашому пошуковому запиту. Будь ласка, спробуйте ще раз!"}),n.style.display="none";return}E(t.hits),c+=1,t.hits.length<u||c>Math.ceil(t.totalHits/u)?(n.style.display="none",l.info({message:"Вибачте, але ви досягли кінця результатів пошуку"})):n.style.display="block"}catch(t){n.style.display="none",l.error({title:"Error",message:t.message})}};n.addEventListener("click",async()=>{await p();const t=document.querySelector(".gallery").lastElementChild.getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
